### ISSUE TITLE
Field sometimes has focus on page load

### ISSUE THREAD

**Issue by nathanhornby** [hananils/datetime#163]
I haven't worked out what triggers it - but sometimes when entering an entry this field will be 'exposed' and have focus, sometimes it doesn't.

Although I love the visuals of this extension it does take up a lot of real-estate when 'exposed' so would be better if it didn't do it on page load (IMO), and only when a user interacts with it.

**Comment by nitriques** [comment]
@nathanhornby The collapsible *has* to start open for performance reason. I know it's not super awesome, but this is more of a core issue. Closing for now.

**Comment by nathanhornby** [comment]
Hi @nitriques  - technically the primary issue was (at least when reported) that often the field would gain focus on page load, irrelevant of its position. That's an accessibility issue.

The auto collapsing was more of a personal preference.

**Comment by nitriques** [comment]
Ok, I'll keep an eye open if I see weird focuses.

But if the field is the first field of the section, it will focus it automatically (sorry if this has already been said)

**Comment by nitriques** [comment]
BTW @nathanhornby I am working on a fixed version for both 2.5 and 2.6.

Would you mind testing it (when ready) ?

**Comment by nathanhornby** [comment]
I certainly will if I get the chance - I haven't been working on many Symphony projects recently so I'm a bit out of the loop!

**Comment by nitriques** [comment]
Ok thanks Nathan.
