### ISSUE TITLE
I can not refer to a record with a field of type Date and Time.

### ISSUE THREAD

**Issue by reallyalexpro** [hananils/datetime#166]
Section with a given field is not listed when you set up the fields of reference type.
https://www.dropbox.com/s/pp8iqi5glqrkwqp/Section%20with%20Date%20and%20Time%20field.png?dl=0
https://www.dropbox.com/s/pq5f7t6y4brjipr/New%20section%20with%20reference.png?dl=0

**Comment by nitriques** [comment]
What version of Symphony are you running ? And what version of datetime ?

**Comment by nitriques** [comment]
Closed as I have no feedback in two weeks.
