### ISSUE TITLE
Default Date Format

### ISSUE THREAD

**Issue by nilshoerrmann** [hananils/datetime#170]
If – for some reason – the date format setting is missing in the configuration file, the field currently displays no date and time in the input field: only the widget is visible (and it visualises the correct date).

This field should have a fallback date format to catch this case.

**Comment by nitriques** [comment]
> This field should have a fallback date format to catch this case.

Ok, I agree. But which one ? ISO (YYYY-MM-DD) ? I would agree with this, since it is the only logical dateformat for me. But that would pissed off any American  hahaha

**Comment by nilshoerrmann** [comment]
The format doesn't matter at all – as long as the extension doens't just return an empty string :)

**Comment by nitriques** [comment]
ok!

**Comment by nilshoerrmann** [comment]
Thanks a lot, Nicolas!

**Comment by nitriques** [comment]
My pleasure!
